# Generated by Django 3.1.6 on 2021-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'いいね'), ('Unlike', '解除')], max_length=8),
        ),
    ]
